xlab-si/emmy

- common/common.go
- common/polynomials.go
- common/storage.go
- dlog/ecdlog.go
- dlog/zp_dlog.go
- dlogproofs/dlog_equality.go
- dlogproofs/dlog_equality_blinded_transcript.go
- encryption/cspaillier.go
- encryption/paillier.go
- pseudonymsys/ca.go
- pseudonymsys/org_c_issue.go
- pseudonymsys/org_c_transfer.go
- pseudonymsys/org_nym_gen.go
- pseudonymsys/org_nym_gen_verify_master.go
- pseudonymsys/user_c_issue.go
- pseudonymsys/user_c_transfer.go
- pseudonymsys/user_ca_register.go
- pseudonymsys/user_nym_gen.go
- secretsharing/dealer.go
- signatures/cl.go
- test/common_test.go
- test/encryption_test.go
- test/signatures_test.go
Until now, some of the individual `.go` files have already been go-formatted with the
`gofmt` tool, but most of them were not. Commit in this PR applies go formatting to the
entire go code base in order to keep the formatting clean and consistent.
> Go-formatting the project

- log/logging.go
This commit adds a TurnOff function to emmy's logging package. The function
is useful for suppressing otherwise intentionally verbose logging, which is not 
always desired (for instance, when running tests or benchmarks).
> Enable log suppression

- emmy.go
- server/server.go
- test/communication_test.go
Until now, the `Server` struct and corresponding `NewProtocolServer` initializer in `server/server.go` were empty, so code in `emmy.go` and `test/communication_test.go` had to take care of server initialization, starup and teardown. This commit modifies the Server struct by enclosing the` *grpc.Server`,  which allows setup and teardown directly via `Server` struct, resulting in simplified server management in tests and in `emmy.go`.
> Improve server setup and teardown logic

- test/common_test.go
- test/communication_test.go
- test/dlog_test.go
- test/encryption_test.go
- test/pseudonymsys_ec_test.go
- test/pseudonymsys_test.go
- test/signatures_test.go
This commit renames the package with unit tests to 'test', like the parent folder. It also removes a typo in the name of a global variable.
This is not refactoring of logic per-se, only a couple of really minor changes that need to be taken care of before proceeding with further changes in the package with unit tests.
> Minor refactoring of test package

- client/client.go
- client/cspaillier.go
- client/pedersen.go
- client/pedersen_ec.go
- client/pseudonymsys.go
- client/pseudonymsys_ca.go
- client/pseudonymsys_ca_ec.go
- client/pseudonymsys_ec.go
- client/schnorr.go
- client/schnorr_ec.go
- emmy.go
- test/communication_test.go
- test/pseudonymsys_ec_test.go
- test/pseudonymsys_test.go
This commit moves creation of `*grpc.ClientConn` outside protocol clients. Instead of server `endpoint string`, clients are now passed a connection, which allows us to:
* re-use a single connection across several protocol clients
* reduce some initialization overhead when running tests (and in future benchmarks)
* avoid an issue with exhausted file descriptors in case we are starting too many connections, which occurs when starting thousands of concurrent clients on the same host
Inside main client functions executing crypto protocols, you will notice that once the protocol finishes we are not manipulating (closing) connection anymore, but gRPC streams. E.g., instead of this:
```go
if err := c.close(); err != nil { ... } // closes gRPC connection
```
we are now doing:
```go
if err := …
```
> Create gRPC connections outside protocol clients

- README.md
- client/client.go
- emmy.go
- log/logging.go
- server/server.go
- test/communication_test.go
In this commit we modify the `logging` package in order to be more conveniently used by other (mainly `client`, `server` and `test`) packages. The default log level set by logging package's `init()` function is *info*. However for tests, we're now explicitly setting the loglevel to *debug*. The log levels are standard ones, e.g. *debug*, *info*, *notice*, *error* and *critical*.
The loglevel flag was also added to emmy CLI in order to give the end user some more control. The end user interacting with the CLI app can now control the log level like this:
````bash
$ emmy example --loglevel notice  # or '-l notice'
$ emmy server start --loglevel info # we can omit this, as info is the default log level
$ emmy client --protocol schnorr -l debug
````
I didn't  update the CLI app usage …
> Add support for controlling log levels

- cli/server.go
- server/server.go
This commit introduces a simple fix that reports an error instead of panicking when the server cannot be started due to an error emitted by `net.Listen(port)` call. This happens, for instance, when a port we want our server to listen on is occupied. 
The server CLI command now catches such errors and displays them to the user.
For instance, if we start the server via `emmy server start` in two terminal windows, the command in the second terminal window will display
```bash
$ emmy server start
2017/09/13 08:03:09 [server] 08:03:09.497 NewProtocolServer ▶ INFO 001 Instantiating new protocol server
2017/09/13 08:03:09 [server] 08:03:09.497 NewProtocolServer ▶ INFO 002 Registering services
2017/09/13 08:03:09 [server] 08:03:09.498 NewProtocolServer ▶ INFO 003 Successfully read certificate …
```
> Don't panic when server port is occupied

- crypto/pseudonymsys/ca.go
- crypto/pseudonymsys/ca_ec.go
- crypto/pseudonymsys/org_issue.go
- crypto/pseudonymsys/org_issue_ec.go
- crypto/pseudonymsys/org_nym_gen.go
- crypto/pseudonymsys/org_nym_gen_ec.go
- crypto/pseudonymsys/org_transfer.go
- crypto/pseudonymsys/org_transfer_ec.go
- server/pseudonymsys.go
- server/pseudonymsys_ca.go
- server/pseudonymsys_ca_ec.go
- server/pseudonymsys_ec.go
Previously `crypto/pseudonymsys` package extensively used config loading directly via `config.LoadSomething()` functions, when all other protocols are loading it from grpc
wrappers. In this commit, config loading was moved from `crypto/pseudonymsys` files to pseudonymsys grpc clients, since it will be easier to improve configuration handling across emmy in future, if crypto backend isn't concerned with it.
I also added public key parameters to `OrgNymGen` and `OrgNymGenEC` structs to avoid passing them to their `GetChallenge` functions, since this is the way it's already implemented for other pseudonymsys structs.
> Remove config loading from crypto/pseudonymsys

- README.md
- cli/client.go
- cli/flags.go
- client/client.go
- client/tls.go
- test/communication_test.go
- test/tls_test.go
Since #17, client and server use TLS to secure channel over which they communicate. However, for development and testing purposes we sometimes want to avoid errors stemming from the server's use of self-signed cert. 
In this PR we:
* add an additional parameter to client's `GetConnection()`, which specifies whether to avoid checking of server's CA cert chain and hostname. 
* Update the calls in the test code and client CLI code.
* Update README with explanation and examples that demonstrate the purpose and usage of the `--insecure` flag.
> Allow insecure TLS connections 

- cli/client.go
- client/pedersen_ec.go
- client/pseudonymsys_ca_ec.go
- client/pseudonymsys_ec.go
- crypto/commitments/pedersen_ec.go
- crypto/dlog/ec.go
- crypto/dlogproofs/schnorr_ec.go
- crypto/pseudonymsys/ca.go
- crypto/pseudonymsys/ca_ec.go
- crypto/pseudonymsys/org_issue_ec.go
- crypto/pseudonymsys/org_nym_gen.go
- crypto/pseudonymsys/org_nym_gen_ec.go
- crypto/pseudonymsys/org_transfer_ec.go
- server/pedersen_ec.go
- server/pseudonymsys_ca_ec.go
- server/pseudonymsys_ec.go
- server/schnorr_ec.go
- server/server.go
- test/communication_test.go
- test/pseudonymsys_ec_test.go
Until now, it was assumed that all schemes implemented in EC use `crypto/dlog.P256` curve type (e.g. it was fixed and all parts emmy assumed that this is the appropriate curve type). This PR allows *a bit* more control over the choice of curves used for elliptic cryptography. 
Note that some schemes rely on elliptic curves even though they are not themselves implemented in EC space - for instance, you will notice that modular implementation of pseudonymsys CA also uses elliptic curves for signatures. In such cases, curves remain fixed to `dlog.P256`.
In a real world setting, client is aware of the curve type to be used for communication with a given server. 
Server also has this parameter fixed; for now, we set it once, and the same one is used for all schemes implemented in EC, …
> Make curve configurable for EC schemes

- client/pseudonymsys.go
- client/pseudonymsys_ec.go
- crypto/zkp/primitives/dlogproofs/dlog_equality_blinded_transcript.go
- crypto/zkp/primitives/dlogproofs/dlog_equality_blinded_transcript_ec.go
- crypto/zkp/schemes/pseudonymsys/org_issue.go
- crypto/zkp/schemes/pseudonymsys/org_issue_ec.go
- server/pseudonymsys.go
- server/pseudonymsys_ec.go
This commit introduces Transcript struct in the dlogproofs package. It greatly improves readability. In addition, it will allow us to easily achieve compatibility with types supported by go tools for creating language bindings.
Resolves #33.
> Make transcript a struct in dlogproofs package

- config/config.go
This commit swaps `serviceProvider` and `serviceDescription` arguments that were accidentally passed in an incorrect order to `NewServiceInfo` function call within `config.go`'s `LoadServiceInfo`.
> Swap service description and provider in LoadServiceInfo

- server/server.go
This commit updates calls to `fmt.Errorf` function in `server.go`. Previously format and arguments were not provided appropriately, which can potentially fail the `go test` command in latest version of Go, as a consequence of `go vet` emitting errors.
This solves the problem of tests failing for #49.
> Update calls to fmt.Errorf in server.go

- README.md
- cli/flags.go
- cli/server.go
- client/client_test.go
- server/registration_manager.go
- server/server.go
This PR adds a new `--db` flag to `emmy server` CLI command. The flag should point to the address of the redis database that will hold registration keys. This allows us to override the default value (read from `config/defaults.yml`) at server startup. 
Address of the redis database is now also passed to the initializer of the `Server` struct. 
At the same time, since it's all very minor and related, this PR also:
* updates the README with updated instructions (description of the `--db` flag),
* increases logged severity of not being able to connect to redis at a given address to *critical*,
* improves the error message that gets reported when server cannot connect to redis instance at startup.
> Add redis address CLI flag to emmy server command

- server/pseudonymsys.go
- server/pseudonymsys_ca.go
- server/pseudonymsys_ca_ec.go
- server/pseudonymsys_ec.go
- server/server.go
This PR improves the way protocol errors are handled by emmy server.
So far, we only reported `ProtocolError`s back to the client in case any of pseudonym system protocols failed. However, these errors were not consistently logged at the server side. Here's a summary of changes:
* added logging for all `ProtocolError`s at the server side with the *error* severity level - so far we were only able to see these errors in one of the protocols, and only if the log level of `Server`'s logger was *debug*. Now we'll be able to detect these errors more quickly, as they will be shown in the server's log even if it's not running in debugging mode.
* the `Server`'s `send()` function is updated to more precisely log the type of message that was sent (either `msg.Content` or `msg.ProtocolError`). 
* …
> Improve server-side handling of protocol errors

- log/formats.go
This commit adds a definition of `FORMAT_SHORT_COLORLESS` to `log/formats.go`. It is analogous to our existing `FORMAT_SHORT`, but doesn't contain any color information. This is especially appropriate for logging on mobile clients, where color information is not needed (or not interpreted at all, which is why we get unwanted symbols displayed among the logging messages).
> Add short colorless format to logging formats

- client/pseudonymsys_ca.go
- client/pseudonymsys_ca_ec.go
- client/pseudonymsys_ec_test.go
- client/pseudonymsys_test.go
This commit adds `GenerateMasterNym` function to `PseudonymsysCAClient` and `PseudonymsysCAClientEC` in order to simplify master pseudonym generation for the client.
Logic for master nym generation was moved from pseudonymsys test code and replaced with calls to newly introduced functions.
> Implement GenerateMasterNym functions

- Dockerfile
- docker-compose.yml
- docs/develop.md
This commit adds a Dockerfile for building emmy server image. In addition, docker-compose file is added that starts emmy server container as well as redis container. 
These are added solely for convenience during development; the use of dockerized components is not assumed during unit testing on a given host or for Travis CI builds.
Brief guidelines and instructions were added to `docs/develop.md`.
> Add Dockerfile and docker-compose file

- crypto/common/decomposition.go
- crypto/common/decomposition_test.go
This commit adds implementation of Lipmaa's algorithm for calculating the lagrangian of a given non-negative integer, as described in [this paper](https://www.iacr.org/cryptodb/archive/2003/ASIACRYPT/353/353.pdf). 
Given an arbitrary non-negative integer *n*, the algorithm efficiently computes the roots *w<sub>1</sub>, w<sub>2</sub>, w<sub>3</sub>, w<sub>4</sub>*, so that, when squared, the roots add up to exactly *n* (*n = w<sub>1</sub><sup>2</sup> + w<sub>2</sub><sup>2</sup> + w<sub>3</sub><sup>2</sup> + w<sub>4</sub><sup>2</sup>*).
This algorithm will be used in the future to support implementation of range proofs.
> Implement Lipmaa's decomposition of non-negative integers

- client/client.go
- client/client_test.go
- client/pedersen.go
- client/pedersen_ec.go
- client/pseudonymsys_ec_test.go
- client/pseudonymsys_test.go
- client/schnorr_test.go
- crypto/encryption/cs_paillier.go
- crypto/encryption/paillier.go
- crypto/signatures/cl.go
- crypto/zkp/primitives/dlogproofs/schnorr.go
- crypto/zkp/primitives/qrproofs/qnr.go
- server/server.go
- server/session.go
This PR implements several minor corrections that silence megacheck, misspell and gosimple linters, so that they no longer emit specific warnings. It fixes:
* all misspellings,
* removes all split declarations and immediate assignments afterwards,
* replaces unused variables (errors) in test code with `_`,
* adds error handling where it was missing.
Several improvements could still be made, as these changes don't cover all the warnings reported by the above mentioned linters, nor do we consider the output of other important linters (to be discussed in future).
> Implement corrections suggested by linters

- .travis.yml
- Makefile
- docs/develop.md
This PR adds a *Makefile* with several targets for ease of testing and development. Instructions in the Travis CI file were updated so that `make` commands are used. 
Most importantly, documentation in `docs/develop` was also updated and improved on several places, so that the possibility of using `make` targets is reflected where appropriate.
> Use Makefile for a simplified build

- client/compatibility/group.go
- client/compatibility/pseudonymsys.go
- client/compatibility/pseudonymsys_ca.go
- client/pseudonymsys.go
- client/pseudonymsys_ca.go
- client/pseudonymsys_test.go
This PR slightly modifies `PseudonymsysClient` and `PseudonymsysCAClient` initializer functions by adding a parameter of type `groups.SchnorrGroup`.
Until now, initializer functions merely constructed schnorr group from the values provided in the configuration file (or, for mobile clients, which had no means of passing their own configuration file, the defaults were loaded). Schnorr group is now generated externally and passed to  both initializers. This allows mobile clients to specify their own (non-default) schnorr group, which was previously not possible.
PS: This is how it's already done for all other clients as well - if a protocol needs `SchnorrGroup`, then it is constructed outside and passed to initializer, for instance see `NewQRClient`, `NewSchnorrClient` and others in the …
> Pseudonymsys clients' initializers accept group parameter

- crypto/zkp/schemes/pseudonymsys/keygen.go
This commit adds functions for generation of key pairs to be used with pseudonym system scheme (both EC and modular version). Currently these functions are unused, as server-side relies on using fixed values that are loaded from config, so using these functions in test code breaks the tests. 
These functions are for future convenience - when configuration of cryptographic parameters is improved, these functions will be called during the initial setup of pseudonym system CA and organizations.
In addition, I plan to implement structs `SecKey`, `PubKey` and `PubKeyEC` shortly, so I added two TODOs above new function definitions, since the planned change will affect their return values.
> Add keypair generation functions for pseudonym system

- client/compatibility/doc.go
- client/compatibility/pseudonymsys.go
- client/compatibility/pseudonymsys_ec.go
- client/pseudonymsys.go
- client/pseudonymsys_ec.go
- client/pseudonymsys_ec_test.go
- client/pseudonymsys_test.go
- config/config.go
- crypto/zkp/schemes/pseudonymsys/ca.go
- crypto/zkp/schemes/pseudonymsys/ca_ec.go
- crypto/zkp/schemes/pseudonymsys/keygen.go
- crypto/zkp/schemes/pseudonymsys/org_issue.go
- crypto/zkp/schemes/pseudonymsys/org_issue_ec.go
- crypto/zkp/schemes/pseudonymsys/org_nym_gen.go
- crypto/zkp/schemes/pseudonymsys/org_nym_gen_ec.go
- crypto/zkp/schemes/pseudonymsys/org_transfer.go
- crypto/zkp/schemes/pseudonymsys/org_transfer_ec.go
- server/pseudonymsys.go
- server/pseudonymsys_ca.go
- server/pseudonymsys_ca_ec.go
- server/pseudonymsys_ec.go
This PR introduces three new structs: `PubKey`, `PubKeyEC` and `SecKey` that represent  public keys for both implementations of pseudonym system scheme, and their secret keys, which are of the same type
for both implementations. `PubKey` and `PubKeyEC` are not only a different naming for our previous `OrgPubKeys` and `OrgPubKeysEC` types (these were removed), but are more generic, since CA's also have their corresponding `PubKey`.
Several structs and functions from the `pseudonymsys` package previously accepted parameters in the form of: `s1, s2 *big.Int`, `h1, h2 *groups.ECGroupElement` or similar - this PR modifies such structs and functions so that they accept appropriate key struct types.
Packages `client,` `compatibility`, `server` and `config` were updated in light of these changes. …
> New structs for pseudonym system keys

- Makefile
- emmy.go
This commit adds copyright and version information to the emmy CLI command. Version can be set with the new `release` target in the *Makefile*.
By running `make release version=0.0.1`, we get `emmy` binary, and running it shows us the following:
```bash
$ emmy
NAME:
emmy - A CLI app for running emmy server, emmy clients 
and examples of proofs offered by the emmy library
USAGE:
emmy [global options] command [command options] [arguments...]
VERSION:
0.0.1
COMMANDS:
server   A server (verifier) that verifies clients (provers)
client   A client (prover) that wants to prove something to the server (verifier)
help, h  Shows a list of commands or help for one command
GLOBAL OPTIONS:
--help, -h     show help
--version, -v  print the version
COPYRIGHT:
(c) 2017 XLAB d.o.o.
Licensed under Apache …
```
> Add version and copyright info to CLI

- crypto/commitments/damgard-fujisaki.go
- crypto/zkp/primitives/commitments/damgard-fujisaki_equality.go
- crypto/zkp/primitives/commitments/damgard-fujisaki_equality_test.go
- crypto/zkp/primitives/commitments/damgard-fujisaki_multiplication_test.go
- crypto/zkp/primitives/commitments/damgard-fujisaki_square.go
- crypto/zkp/primitives/commitments/damgard-fujisaki_square_test.go
DFCommitmentEqualityProof proves that the two commitments c1, c2 hide the same number. Given c1, c2, prove that c1 = g1^x * h1^r1 (mod n1) and c2 = g2^x * h2^r2 (mod n2) for some x, r1, r2 (note that both commitments hide x).
DFCommitmentSquareProof proves that the commitment hides the square. Given c, prove that c = g^(x^2) * h^r (mod n).
> DamgardFujisaki commitment equality and square proof

- server/info.go
- server/pedersen.go
- server/pedersen_ec.go
- server/pseudonymsys.go
- server/pseudonymsys_ca.go
- server/pseudonymsys_ca_ec.go
- server/pseudonymsys_ec.go
- server/registration_manager.go
- server/server.go
- server/session.go
This PR exports structs `SessionManager` and `RegistrationManager` defined in the `server` package. In addition, `Server`'s fields `grpcServer` and `logger` are now also exported. 
These changes will provide more flexibility, as they will allow (future) implementations of server-side RPC handlers for specific schemes to reside outside our current `server` package. This means possibility of better organization of server-side implementations, which is a pending task at this point.
Consider this case: we currently have all server-side RPC handlers implemented in the `server` package, and all these handlers are hooked to our `Server` struct. So, basically, our server supports all the services defined in our protobuffers specification at once.
As discussed offline, we don't want this on the …
> Export Server's fields and structs

- client/client.go
- client/pseudonymsys.go
- client/pseudonymsys_ec.go
- proto/messages.proto
- server/pseudonymsys.go
- server/pseudonymsys_ca.go
- server/pseudonymsys_ca_ec.go
- server/pseudonymsys_ec.go
- server/server.go
This commit removes custom `ProtocolError` protobuffer message that was previously a part of our `Message` message type for reporting non-grpc related errors that can occur during the execution of interactive protocols.
Instead, when a protocol error happens, we simply return the error with `return status.Error(<code>, <messageA>)` from the RPC handler, which is a standard way of reporting RPC errors to clients. According to [grpc status package docs](https://godoc.org/google.golang.org/grpc/status), all RPC handlers should return an error created by this package.
As a consequence, client's `send` and server's `receive` functions are simplified, because there's no need for additional logic that catches `ProtocolError`s, as they are now reported as normal `error`s. This change also affects …
> Remove ProtocolError message

- crypto/zkp/primitives/dlogproofs/schnorr.go
- crypto/zkp/primitives/qrspecialrsaproofs/representation.go
- crypto/zkp/primitives/qrspecialrsaproofs/representation_test.go
Representation proof is like Schnorr proof but in a QRSpecialRSA group instead of Schnorr group.
Signed-off-by: miha <stopar.miha@gmail.com>
> Representation proof for QRSpecialRSA implemented.

- crypto/df/lipmaa_decompose.go
- crypto/df/lipmaa_decompose_test.go
- crypto/df/positive_commitment.go
This PR moves Lipmaa decomposition functionality from `common` package to `df` package, since this is the only place where it is used. It is now unexported. 
Some tests were renamed for consistency and brevity, and an import of assert package was fixed.
> Move Lipmaa decomposition to df package

- crypto/common/common.go
- crypto/qr/qr.go
- crypto/qr/qr_test.go
- crypto/qr/rsa.go
This commit removes `IsQuadraticResidue` from `crypto/common` package. Its refactored version is now called `IsQR`, and resides in the `crypto/qr` package.
@miha-stopar Please check tests for the function.
> Introduce isQR function in qr package

- .travis.yml
- Makefile
- README.md
- client/client_test.go
- client/pseudonymsys_ec_test.go
- client/pseudonymsys_test.go
- cmd/server.go
- crypto/cl/cred_issue_test.go
- crypto/cl/db_manager.go
- crypto/cl/org.go
- docs/develop.md
- server/cl.go
- server/registration_manager.go
- server/server.go
This PR introduces a couple of changes related to where and how data is accessed via a DB client.
Previously we had two different structs for handling registration keys and for handling receiver records (CL scheme), both wrapping `*redis.Client`.
In place of these two structs we now have two new interfaces, `RegistrationManager` with method `CheckRegistrationKey` and `ReceiverRecordManager` with methods `Store` and `Load`. The former is currently used in server-side handlers in both pseudonym system schemes, and will be integrated with the CL scheme in near future as well. The latter is specific for the server-side handler of the CL scheme, and is thus defined the `crypto/cl` package.
Both interfaces have two implementations: a redis client and a mock implementation. Mock implementations …
> Use interfaces to model DB dependencies

- Dockerfile
- README.md
- docs/develop.md
- docs/theory.md
- log/formats.go
- server/server.go
This commit changes all usages of the library name **Emmy** to **emmy** for consistency.
> Use emmy as library name consistently

- crypto/encryption/cs_paillier.go
- crypto/encryption/cs_paillier_test.go
Closing the other duplicate PRs and opening a new PR here
Removed references to csp.SecKey because the verifier should not need the private key to verify
Also added a final check that abs(v) == v (step 3 of the protocol as described in the paper)
> Add verifiable encryption test
